version: "3.8"

name: lab-6

services:
  backend:
    container_name: lab-6-backend
    build: backend
    environment:
      - NODE_ENV=development
    volumes:
      - "./backend:/app"
    env_file:
      - ./env/postgres.env
    links:
      - db
  db:
    container_name: lab-6-db
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=development_db
    env_file:
      - ./env/postgres.env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      
volumes:
    pg_data:
      external: false
